route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 15m
  repeat_interval: 30m
  receiver: email

templates: 
  - './templates/*.tmpl'

receivers:
- name: email
  email_configs:
  - to: ""
    from: 
    smarthost: smtp.exmail.qq.com:465
    auth_username: 
    auth_password: 
    require_tls: false
    send_resolved: true