groups:
- name: blackbox
  rules:
  - alert: BlackboxProbeFailed
    expr: probe_success == 0
    for: 5m
    labels:
      severity: Critical
    annotations:
      summary: "Instance: {{ $labels.instance }}; Value: {{ $value }}"
      description: "Blackbox probe failed, target instance unreachable."

#  - alert: BlackboxSlowProbe
#    expr: avg_over_time(probe_duration_seconds[1m]) > 10
#    for: 1m
#    labels:
#      severity: Warning
#    annotations:
#      summary: "Instance: {{ $labels.instance }}; Value: {{ $value }}"
#      description: "Blackbox probe took more than 10s(avg) to complete."

  - alert: BlackboxProbeHttpFailure
    expr: probe_http_status_code < 200 OR probe_http_status_code > 399
    for: 5m 
    labels:
      severity: Critical
    annotations:
      summary: "Instance: {{ $labels.instance }}; Value: {{ $value }}"
      description: "Target http status return code is not between 200-400"

  - alert: BlackboxSslCertificateWillExpireSoon
    expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 15
    for: 0m
    labels:
      severity: Warning
    annotations:
      summary: "Instance: {{ $labels.instance }}; Value: {{ $value }}"
      description:  "Target SSL certificate expires in 15 days"

  - alert: BlackboxSslCertificateExpired
    expr: probe_ssl_earliest_cert_expiry - time() <= 0
    for: 0m
    labels:
      severity: Critical
    annotations:
      summary: "Instance: {{ $labels.instance }}; Value: {{ $value }}"
      description: "Target SSL certificate has expired"

  - alert: BlackboxProbeSlowHttp
    expr: avg_over_time(probe_http_duration_seconds[2m]) > 5
    for: 2m
    labels:
      severity: Warning
    annotations:
      summary: "Instance: {{ $labels.instance }}; Value: {{ $value }}"
      description:  "HTTP request took more than 5s to complete"

#  - alert: BlackboxProbeSlowPing
#    expr: avg_over_time(probe_icmp_duration_seconds[1m]) > 3
#    for: 1m
#    labels:
#      severity: Warning
#    annotations:
#      summary: "Instance: {{ $labels.instance }}; Value: {{ $value }}"
#      description: "Blackbox ping took more than 3s(avg) to complete"