global:
  scrape_interval: 60s 
  scrape_timeout: 30s
  evaluation_interval: 60s 

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - localhost:9093

rule_files:
  - "../rules/blackbox.yml"
  - "../rules/node.yml"
  - "../rules/prometheus.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: 
        - "Aliyun-BJ-Prod-002:9090"

  - job_name: "Aliyun-BJ-Prod-001"
    static_configs:
      - targets:
        - "Aliyun-BJ-Prod-001:9100"

  - job_name: 'blackbox-bj'
    metrics_path: /probe
    params:
      module: [http_2xx] 
    file_sd_configs:
    - files:
      - '../rules/bj.json'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement:  # The blackbox exporter's real hostname:port

  - job_name: 'blackbox-ng'
    metrics_path: /probe
    params:
      module: [tcp_connect] 
    file_sd_configs:
    - files:
      - '../rules/ng.json'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement:  # The blackbox exporter's real hostname:port

  - job_name: 'blackbox-us'
    metrics_path: /probe
    params:
      module: [tcp_connect] 
    file_sd_configs:
    - files:
      - '../rules/us.json'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: # The blackbox exporter's real hostname:port